name: hajir
version: 1.0.1+3
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  cached_network_image: ^3.1.0
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  dotted_border: any
  esys_flutter_share_plus: ^2.2.0
  file_picker: ^5.2.5
  firebase_core: ^2.15.1
  firebase_messaging: ^14.6.6
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-alpha.2
  flutter_html_to_pdf: ^0.7.0
  flutter_local_notifications: ^15.1.0+1
  flutter_localizations:
    sdk: flutter
  flutter_native_contact_picker: ^0.0.3
  flutter_otp_text_field: ^1.1.1
  flutter_screenutil: ^5.6.0
  flutter_svg: any
  fluttercontactpicker: ^4.7.0
  fluttertoast: ^8.1.2
  get: 4.6.5
  image_picker: ^0.8.6
  intl: 
  json_annotation: null
  local_auth: ^2.1.3
  path_provider: ^2.0.12
  percent_indicator: ^4.2.2
  permission_handler: ^10.2.0
  # pusher_channels_flutter: ^2.1.2
  qrscan: ^0.3.3
  shared_preferences: ^2.0.15
  shimmer: ^3.0.0
  syncfusion_flutter_charts: ^20.4.41
  syncfusion_flutter_datepicker: ^20.4.54
  tuple: ^2.0.0
  url_launcher: ^6.1.8

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/Vector logo-.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
